### ISSUE TITLE
move command should take destination as a relative path too for local operation

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#1057]
running the following command moves the file from the current directory into the root directory of the dandiset. this seems unintuitive for a unix user.

> /mnt/beegfs/Lee/dandi/sub-MITU01/ses-20211016h18m33s42/micr$ dandi move sub-MITU01_sample-100_photo.jpg sub-MITU01_ses-20211016h18m33s42_sample-100_photo.jpg

**Comment by yarikoptic** [comment]
hm, indeed seems sensible to expect both source and destination paths to be relative to current directory.  Or we are missing some usage pattern which would contradict that @jwodder ?

**Comment by yarikoptic** [comment]
note: I have retitled to be closer to the underlying UX issue.  The original title was "behaves different from unix move" but to answer that one - even though we aimed to stay close to "unix move" semantic in the design of `dandi move`, because we are to operate on both local and remote instances within one command, we might not be able to mimic "unix move" exactly, so we are likely to behave differently and that would be ok IMHO.

**Comment by yarikoptic** [comment]
> seems like this expects the user to know many things. 

like what?  is `dandi move --help` too complicated and/or interface too non-intuitive? 

Please file those ideas as separate issues to discuss and possibly implement.  In this one I think we should address the original problem first since IMHO it goes not inline with what `dandi move --help` says 

```
 In addition, when running the command inside a subdirectory of a
  Dandiset, all paths must be relative to the subdirectory, even if only
  operating on the remote Dandiset.
```

and thus I consider it a bug.

**Comment by yarikoptic** [comment]
> i filed this as a user experience issue rather than a bug (but it is also a bug). i would still say its also user experience issue.

and hopefully we improve user experience having fixed the bug ;)
