### ISSUE TITLE
Cannot move all sub-folders/files into another folder in remote type of operation

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#1081]
I have created a case like 
![image](https://user-images.githubusercontent.com/39889/180278678-92d871a0-a0f1-4d7c-b2e8-346b6087fd11.png)

to replicate the scenario we need to have/do for 000026.  Now I wanted to move those two folders under the top directory but it failed likely thinking that `.` is the filename, not a folder.

```
$> dandi move --work-on remote --regex -d 'https://dandiarchive.org/dandiset/000029/draft' 'subjects/.*' . 
2022-07-21 13:34:30,231 [    INFO] Fetching list of assets for Dandiset 000029
2022-07-21 13:34:30,377 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20220721173427Z-659412.log
Error: Remote assets 'subjects/sub-anm369962/sub-anm369962_behavior+ecephys.nwb' and 'subjects/sub-anm369963/sub-anm369963_behavior+ecephys.nwb' would both be moved to '.'
```

and similar issue was first when I tried to move all `sub-.*` from top level under a new "folder" (we don't have notion of folders on remote):

```
$> dandi move --work-on remote --regex -d 'https://dandiarchive.org/dandiset/000029' 'sub-.*' subjects/       
2022-07-21 13:31:38,927 [    INFO] Fetching list of assets for Dandiset 000029
2022-07-21 13:31:39,048 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20220721173135Z-658912.log
Error: Remote assets 'sub-anm369963/sub-anm369963_behavior+ecephys.nwb' and 'sub-anm369964/sub-anm369964_behavior+ecephys.nwb' would both be moved to 'subjects'
```

so may be there is a need to add semantic to signal that the remote path (`.` or `subjects/`) is to be a "folder"?

**Comment by jwodder** [comment]
@yarikoptic The problem is that you're moving by regex, for which the syntax is `dandi move --regex <pattern> <replacement>`, i.e., the second argument replaces the part of the first argument that matches the filenames.  In the case of `dandi move --regex 'subjects/.*' .`, this has the effect of replacing the entire filename with `.`, and likewise for `dandi move --regex 'sub-.*' subjects/`.

If your goal is to move `subjects/sub-anm369962/` to just `sub-anm369962/`, you should be able to do that without using a regex with just:

    dandi move -d https://dandiarchive.org/dandiset/000029/draft subjects/sub-anm369962/ sub-anm369962

and then likewise for the other directory.

If you're working in a local clone of the repository, you can use the shell's globbing to move both directories at once:

    dandi move -d https://dandiarchive.org/dandiset/000029/draft subjects/* .

If you would like to get this working using regexes, you can strip off the `subjects/` prefix from all assets that have it with:

    dandi move -d https://dandiarchive.org/dandiset/000029/draft --regex subjects/ ""

**Comment by yarikoptic** [comment]
**Thank you** for the explanation -- I apparently forgot how we thought to make `--regex` mode work! 

> and then likewise for the other directory.

somewhat prohibitive -- it takes awhile to "Fetching list of assets for Dandiset 000026" ;)I think it would be great to get some Examples section in `dandi move --help` with e.g. like the one above, but probably made more specific - with anchoring on the front so I don't start moving some deeper `rawdata/` content.

```
dandi move --work-on remote --regex -d 'https://dandiarchive.org/dandiset/000029/draft' --dry-run '^(sub-.*/)' 'subjects/\1'
```

running 

```
dandi move --work-on remote -d 'https://dandiarchive.org/dandiset/000026/draft' --regex "^rawdata/" ""
```
now

**Comment by jwodder** [comment]
@yarikoptic If you want examples added to the documentation, please create a separate issue for that.  Is that all that's still needed for this issue?

**Comment by yarikoptic** [comment]
ok, here is a dedicated issue https://github.com/dandi/dandi-cli/issues/1092
