### ISSUE TITLE
Q: is it needed to open NWBHDF5IO file with load_namespaces=True?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#14]
question to @bendichter (doing it via github so there is trace or I will forget the answer and will ask again ;)):  in `validate` I opened a file via `pynwb.NWBHDF5IO(path, 'r', load_namespaces=True)`. On some files then it causes hdmf to whine that 

```
UserWarning: No cached namespaces found in testfile.nwb
```

so I wondered if for validation I have to (or not) to explicitly request loading of the namespaces?

<details>
<summary>full example with a script to produce that file</summary> 

```shell
/home/yoh/proj/dandi/trash > dandi validate testfile.nwb
/home/yoh/deb/gits/pkg-exppsy/hdmf/src/hdmf/backends/hdf5/h5tools.py:99: UserWarning: No cached namespaces found in testfile.nwb
  warnings.warn(msg)
No validation errors among 1 files

/home/yoh/proj/dandi/trash > cat mksample_nwb.py 
import os
import time
from datetime import datetime
from dateutil.tz import tzlocal, tzutc

tm1 = time.time()

from pynwb import NWBFile, TimeSeries
from pynwb import NWBHDF5IO
from pynwb.file import Subject, ElectrodeTable
from pynwb.epoch import TimeIntervals

t0 = time.time()
print("Took %.2f sec to import pynwb" % (t0-tm1))

filename ="testfile.nwb"
nwbfile = NWBFile('session description',
                  'identifier',
                  datetime.now(tzlocal()),
                  file_create_date=datetime.now(tzlocal()),
                  lab='a Lab',
                  # Keywords cause that puke upon `repr` ValueError: Not a dataset (not a dataset)
                  keywords=('these', 'are', 'keywords')
                 )
t1 = time.time()
print("Took %.2f sec to create NWB instance" % (t1-t0))

with NWBHDF5IO(filename, 'w') as io:
    io.write(nwbfile, cache_spec=False)

t2 = time.time()
print("Took %.2f sec to write NWB instance" % (t2-t1))

with NWBHDF5IO(filename, 'r', load_namespaces=True) as reader:
    nwbfile = reader.read()
    t3 = time.time()
    print("Took %.2f sec to read NWB instance" % (t3-t2))
    print(nwbfile)
    t4 = time.time()
    print("Took %.2f sec to print repr of NWB instance" % (t4-t3))
print(filename)
```
</details>

**Comment by bendichter** [comment]
@yarikoptic In pynwb, you have the option to cache the spec in the file. If the spec is cached, you can tell pynwb to use that spec by setting `load_namespaces` to `True`. This is particularly useful if you are using an extension, because pynwb can automatically infer simple types directly from a cached schema, which means you don't have to install and import that extension before reading the file. pynwb now caches the spec by default, so most newer files have this cached spec, even if no extensions are used. If you set `load_namespaces` to `True` for a file that has no cached spec, it will throw this harmless warning and default to the normal API. I think loading the namespace is a good idea in general. I've never seen it cause any harm, besides this warning.

**Comment by yarikoptic** [comment]
I don't mind loading them if they are available.  My question is pretty much either I should set `load_namespaces` to anything for validation purposes. I.e. would not setting it have any negative effect on validation (some name spaces not validated, as otherwise they would be, or alike)

**Comment by bendichter** [comment]
I would set it to True

**Comment by yarikoptic** [comment]
ok then I will add ignoring of that warning -- there is no need to inform user IMHO about that during `dandi validate`
