### ISSUE TITLE
Troubleshoot and address/workaround flood of recent tests fails on cron

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#1418]
seems to start failing on quite regular basis

![image](https://github.com/dandi/dandi-cli/assets/39889/b762f2ee-61d8-4c60-9125-03c40864314c)

**Comment by jwodder** [comment]
@yarikoptic 

* The failures on March 14 were due to connection issues with dandiarchive.org.
* The failures on March 8, March 12, and March 13 all seem to have been due to connection or server errors with purl.obolibrary.org and/or ontobee.org.
* The failure on March 10 was due to one run hitting a race condition (I assume) in the tests of `IteratorWithAggregation`.

**Comment by yarikoptic** [comment]
thank you @jwodder , and the most recent one passed. Ok, let's hope that we scared it enough and it would be all good and green now.
