### ISSUE TITLE
Make sure we pass fscacher types it expects

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#1451]
spotted in 
- https://github.com/dandi/dandi-cli/issues/1450

```
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/fscacher/cache.py:133: in fingerprinter
    path = op.realpath(path_orig)
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/posixpath.py:390: in realpath
    filename = os.fspath(filename)
E   TypeError: expected str, bytes or os.PathLike object, not RemoteReadableAsset
```

**Comment by jwodder** [comment]
This is deliberate and not a problem.  `dandi.metadata.nwb.get_metadata()` needs to be able to accept a string, path, or `Readable` instance; it is decorated with an fscacher cache; and passing a non-string, non-path value to an fscacher-cached function simply results in the underlying function being called directly instead of using the cache:

https://github.com/con/fscacher/blob/e52aaa00ada41a2e2868ca75644d25cd037e6f7b/src/fscacher/cache.py#L132-L138

... and so everything works out.  The only reason you're seeing that error is because the underlying function failed while fscacher was handling the `TypeError`, so the latter got included in the traceback.
