### ISSUE TITLE
CI is running twice on pushes to local PRs

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-cli#161]
When a pull request is created from a branch in this repository (rather than from a fork) and then later the branch is pushed to, GitHub Actions runs twice, once for the push and once for the update to the PR.  This results in double the notifications should the CI fail.

**Comment by yarikoptic** [comment]
I have mentioned those too and thought to disable (somehow) those for push, but decided against as long as our testing runs are relatively fast.  I have decided against since some times it results in one failing and another succeeding and it provides information:
- if fails for `push` -- that means that some code path causes trouble as in current state in development of that PR but it would be gone (no longer covered by test? just magically disappearing?) when merged
- if fails for `pull` -- tests pass on development, but then if merged, would fail -- "rebase" or "merge" is due to bring those failures to the development environment

With that in mind I would just keep it as is for now, and we might reconsider it later, unless there is some negative effect we want to mitigate (beyond twice more notifications) -- then reopen please.
