### ISSUE TITLE
Ensure that dataset id is not treated as int

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#302]
yesterday I had managed to run `backups2datalad.py` while omitting leading `0` it its name (`00005` instead of `000005`).  Script managed to proceed while accessing `000005` but locally creating `00005`, so it feels that somewhere it is assumed that dataset id is an int.  IMHO should be more restrictive and treat identifier as a string.

**Comment by jwodder** [comment]
@yarikoptic This issue is due to `https://dandiarchive.org/dandiset/005/draft` being redirected to `https://gui.dandiarchive.org/#/dandiset/000005/draft`, which is caused by [this code in `redirector`](https://github.com/dandi/redirector/blob/db6b4e51ce67b25f22d3332f8c6ed1ec05f742cf/serve.py#L130-L136).

**Comment by yarikoptic** [comment]
thanks, submitted a PR quickly while in the browser ;)

**Comment by yarikoptic** [comment]
to be addressed in redirector, not worth keeping open here
