### ISSUE TITLE
populate 'wasDerivedFrom'

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#385]
Originally posted by @satra in https://github.com/dandi/dandi-api-datasets/pull/6#issuecomment-778664746 :

    wasDerivedFrom is intended to be a chain of biosamples from cell id, slice id, tissuesample id, to subject id.

"chain" here is nesting, i.e. that cell biosample should have wasDerivedFrom pointing to slice and so on.  Any particular level could be skipped if not present

**Comment by satra** [comment]
@yarikoptic - the alternative is not to chain but just add those properties to BioSample for now. wdyt?

**Comment by yarikoptic** [comment]
Do you think it would make it easier,  i.e. is the hierarchy `cell id, slice id, tissuesample id, to subject id.` is not well defined?   Meditor web UI might become  a bit unhappy, but I do not see this particular case really problematic for that.

**Comment by satra** [comment]
> meditor doesn't edit asset metadata and i don't think we would allow asset editing online yet.

i'm thinking of situations where there could be graphs and also at least for one dataset we have probe id instead of cell id.

i think it would make it easier since one would just need to have one biosample object and could remove `wasDerivedFrom` for now.  this would also allow us to simply create a biosample spreadsheet for people to fill in things that are not in NWB, (and to augment NWB with a dandi specific simple object).

(of course these things are never simple in the long run, and once we get more provenance at the biosample level things will get more complicated.)

i'm trying to balance generic prov with custom solution for now. the current formulation is definitely more generic. was hoping to move forward with a simpler solution. we can always update to more complicated form with assetmeta schema upgrade.
