### ISSUE TITLE
fscache validation of the files (taking hdmf, h5py, pynwb, dandi versions as tokens)

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#430]
to speed up reruns in dandi-api-datasets

**Comment by jwodder** [comment]
@yarikoptic 

It turns out that `validate_file()` is already cached.  However:

* `validate_dandi_nwb()` uses the environment variable `DANDI_SCHEMA` as one of the methods to enable validation against the new schema.  As long as that is supported, caching won't work entirely right.
* Using `validate_file()` in dandi-api-datasets means that (a) PyNWB errors will be grouped together with validation errors, and (b) tracebacks won't be reported in the errors files, only the error messages.  Do you care about that?

**Comment by yarikoptic** [comment]
- good catch on `DANDI_SCHEMA` env var.  I guess we are doomed to add it to tokens (if present) for now.
- (b) what tracebacks do you have in mind? I thought that if there is an exception raised by a `fscached` function, we do not memoize that, so exception should be raised again.  
- (c) don't we fscache reading metadata as well?

**Comment by jwodder** [comment]
@yarikoptic 

> good catch on DANDI_SCHEMA env var. I guess we are doomed to add it to tokens (if present) for now.

That wouldn't work if the value of `DANDI_SCHEMA` changes after importing `dandi`.  I would recommend just eliminating `DANDI_SCHEMA` and using the `schema_version` argument to select the new schema.

> what tracebacks do you have in mind?

Tracebacks like the ones [seen here](https://github.com/dandi/dandi-api-datasets/blob/0f6643b59d100d3f4f79406de9bfe5ab31690435/000006/CONVERSION.errors).

> I thought that if there is an exception raised by a fscached function, we do not memoize that, so exception should be raised again

The fscached `validate_file()` should only raise an exception when given an invalid schema version.  Any other exceptions raised inside are returned as a list of strings.  Currently, instead of calling `validate_file()`, `populate_dandiset_asset_yamls.py` copies its code in order to get access to the actual exceptions and their tracebacks.

> don't we fscache reading metadata as well?

No.  There's a cache named "dandi-metadata", but it's for a pynwb function.

**Comment by yarikoptic** [comment]
>  I would recommend just eliminating DANDI_SCHEMA and using the schema_version argument to select the new schema.

+ 1

I guess we could sacrifice printout of tracebacks for now.  We would need to re-approach the whole validation setup which grew to being "too organically" and entrenched into nwb ecosystem.  We are to RF it to support other standards and validators (ref: #431 )
