### ISSUE TITLE
add bids validation support

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#431]
since we may be getting more bids dandisets, we should start providing bids validation support.

**Comment by yarikoptic** [comment]
I wonder which route should we go -- demand/ship full blown JS bids-validator or may be just go (at least start with) https://github.com/bids-standard/bids-validator#python-library .  I expect it to be improved in near future to make use of now machine readable bids-specification/src/schema (just filed https://github.com/bids-standard/bids-validator/issues/1202 since found no existing issue on that end yet).

**Comment by satra** [comment]
does it check for required keys in json files? for some of these datasets coming from k-space reconstructions without dicoms, we may want to need to enable that.

**Comment by yarikoptic** [comment]
the new `src/schema` AFAIK doesn't yet specify json sidecar fields yet :-/ not sure what JS bids-validator does
