### ISSUE TITLE
RF/BF: adjust dandi-api `upload` for changes in the API

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#478]
https://github.com/dandi/dandi-api/pull/156 which followed https://github.com/dandi/dandi-api/pull/150 was merged and deployed, DB wiped clean, blank dandisets reuploaded. 

- `dandi-cli upload` needs to be adjusted to reflect API changes.
- would need to sit on top of #474 since we would need to compute/provide dandi-etag to the API
- adjusted dandi-cli should be tried on uploads of small and large files across available dandisets

**Comment by jwodder** [comment]
@yarikoptic @dchiquito So the changes that affect the CLI side are:

* The payload to & response from the `/uploads/initialize/` endpoint have changed; it now returns a UUID which needs to be included in the paths of the `/uploads/complete/` and `/uploads/validate/` endpoints.
    * The payload now needs to include a hash of the file; what algorithms are accepted here?
* The payload to the `/uploads/validate/` endpoint is gone.
* An ETag digest for the uploaded file needs to be provided, but where?  In the metadata or in the payload to `/uploads/initialize`?
* The `/uploads/validations/{filehash}/` endpoint is gone; should the related functionality just be removed from the CLI?
* Currently, the CLI starts out an upload by making a request to `/uploads/validate/` with the sha256 digest of the file in order to check whether the blob has already been uploaded to the server; what is the equivalent way to do this now?
* Anything else?

**Comment by dchiquito** [comment]
@jwodder
* `/uploads/initialize/` should take a body like this:
```
{
  "contentSize": 12345,
  "digest": {
    "algorithm": "dandi:dandi-etag",
    "value": "..."
  }
}
```
The value should be calculated using the `DandiETag` thingy that's being added to dandi.core. This value is the ETag digest for the file being uploaded.

* The background processes no longer block the CLI, so yes, there is no reason for the CLI to wait for them to finish. After calling `POST /dandisets/{versions__dandiset__pk}/versions/{versions__version}/assets/` the CLI is done with the upload.

* You can call `POST /blobs/digest/` with `{"algorithm": "dandi:dandi-etag", "value": "..." }`. Alternatively, if you try to start the upload with `/uploads/initialize`, it should throw an error 409 with the `Location` header set to the UUID of an existing asset blob, if an asset blob with a matching etag exists.

**Comment by dchiquito** [comment]
@jwodder I made a small change to `/uploads/{uuid}/validate/`, it now returns a 200 with a description of the asset blob for the uploaded data. Since another upload may have completed before yours, the UUID is not necessarily the same as the upload UUID, so you should use the UUID from the response instead of the upload UUID.

**Comment by jwodder** [comment]
@dchiquito Are the `object_key` and `upload_id` fields in the response from `/uploads/initialize/` still used for anything?  Previously, they were passed to `/uploads/complete/` and `/uploads/validate/`, but now they seem to be unused.

**Comment by yarikoptic** [comment]
Eh, too many UUIDs here without clear demarcation of their domain, and I think that is what leads to confusion.  I wonder if we shouldn't better give them dedicated names (`upload_id`, `blob_id` or `blob_key`) even if values would be UUIDs and leave `uuid`  to refer solely to assets?  
Per https://github.com/dandi/dandi-api/pull/150/files#diff-c96d4444d1714a52d5d08dd92d94919393a7db8ded038aa84f02ba1075d2c25eR29 (well -- my suggestion there to be precise) where we used dedicated names, it is 
```
8. CLI `POST /uploads/{upload_id}/validate/` <-- `{}` --> `blobs:key`. API
```

so in "uuid"s it would be
```
8. CLI `POST /uploads/{uploads:uuid}/validate/` <-- `{}` --> `blobs:uuid`. API
```
or in other words -- `blobs:uuid` should not be given/known to the user in any other prior `/uploads/{uploads:uuid}/operation` until the `.../validate/`.

**Comment by yarikoptic** [comment]
@dchiquito moreover I do not see any reason to have `upload_id` to be a `uuid`, unlike for `blobs:uuid` AKA `blobs:key` (I would have even kept it called `key` for disambiguation) should be something of consistent length and randomly evenly spread out for blobs keystore, and `assets` should be a globally unique identifier, thus also UUID.

**Comment by dchiquito** [comment]
@jwodder You are correct, `object_key` and `upload_id` are unused. They are still returned because it was convenient to do so, and I did not prune that information aggressively enough.

**Comment by waxlamp** [comment]
I like the idea of using `<resource type>_id` for all such UUIDs. That emphasizes the opaque nature of these UUIDs, and that they are "typed" to the REST API section in which they appear. So I'd suggest using the names `dandi_upload_id`*, `blod_id` and `asset_id` in order to disambiguate. In particular, the endpoint that validates an upload would be `/uploads/{dandi_upload_id}/validate`, and its response would include a field named `blob_id`, referring to the newly created and validated blob.

Yarik, I get where you're coming from w.r.t "id" vs. "key", but I think it's best to call everything an "id" and treat them opaquely. Then there's a kind of uniformity in engaging the API, and the names of the parameters can guide as in how to make use of them.

*Ideally this would be `upload_id`, but that term already has meaning within S3 (as Daniel pointed out), so for further explicitness, we'd use `dandi_upload_id`.
