### ISSUE TITLE
refactoring participant in asset model

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#530]
i would like to refactor participant a little bit.  right now, we conflate identity of participant with information about the participant that can vary across files, sessions, etc.,. currently: `asset wasAttributedTo  participant`

proposal 1:

```
asset
    wasAttributedTo  participant; # but this participant simply contains an identifier and dob/dod. etc.,.
    wasGeneratedBy [ a Session;
                     "start date": session_start_time,
                     "end date": session_end_time,
                     generated ParticipantInfo]
```

and participantinfo would contain information about age, gender, sex, genotype, etc. the session properties can be improved, but this would be one way of linking the asset to participant info, while separating participant out. however, this could mean that the same participant info is generated by different recording sessions, which is not the case.

proposal 2:

```
asset
    wasAttributedTo  [ a Participant 
                       participatedIn [a Session/DataCollection/MeasurementActivity;
                                       generated ParticipantInfo]
```

in prov there is no outgoing relation from an agent. those are implied. so i'm explicitly creating a property that is the inverse of `activity wasAssociatedWith agent` with `agent participatedIn activity` to support jsonld formulation without creating multiple graphs. in jsonld i can map participatedIn as `@reverse` of `wasAssociatedWith`. 

the full scale of provenance could be quite complicated since genotyping, could be done in a different session than calculation of age, etc.,.

proposal 3:

```
asset
    wasAttributedTo  [ a Participant ];
    wasDerivedFrom [a ParticipantInfo;
                    wasAttributedTo [ a Participant] ] .
```

this last one would be simplest formulation on not technically incorrect. since the nwb file contains some of the metadata. and could potentially be qualified with additional provenance about that attribution.

i'm trying to balance simplicity with flexibility with veracity. while we can improve these elements later on but the current formulation we have is very database/user centric rather than information centric. my next goal is to also see how i can simplify the model to best satisfy both use cases through more jsonld manipulation. i tend to approach jsonld simplification by creating the graph and then iteratively recontextualizing into json, so the graph form we choose is important.

@yarikoptic @tgbugs @lydiang  -  what do you think?

**Comment by lydiang** [comment]
Hey @satra,

This maybe not answering your question directly ....

If your "participant" is an instance of some biological system that we are measuring something from, then in general it should not be an prov:agent

The reason is that by definition prov:agent _bears some form responsibility for an activity taking place_. 
And this case, the mouse, organoid, patient etc. does not bear that responsibility, the investigator does.

If we are strictly follow prov then:

```
asset wasGeneratedBy session
session generated asset

session used participant

asset wasDerivedFrom participant
```

However, this is not sufficient because we want to observe that participant over time/conditions. So we will need two level of "participant". 

The first represents "the biological system" (a mouse, a human, a organoid) over its life cycle.
The second a spatiotemporal snapshot (or sample) of the first because technically that is what is used in observation/measuring. 
This separation will allow the same system to be imaged multiple times during its lifetime and postmortem.

To me, this would be the ideal separation. 

```
asset wasGeneratedBy observation_activity
observation_activity generated asset

observation_activity used sample

sample wasGeneratedBy sampling_activity
sampling_activity generated sample

sample_info wasGeneratedBy sampling_activity
sampling_activity generated sample_info

sampling_activity used participant

sample wasDerivedFrom participant
asset wasDerivedFrom sample
asset wasDerivedFrom participant

```

sample_info is entity that hold information about age, sex, genotype (as these can change overtime)

I know that in some cases the "observation_activity" and "sampling_activity" are actually intermingled in time.  But it is helpful for them to be logically separated.

**Comment by lydiang** [comment]
The separation between the "sample", "observation" vs the system being observed is also used in this SOSA ontology.
https://www.w3.org/TR/vocab-ssn/

I really think that it has lots of parallels here with neuroscience research methodologies.

**Comment by lydiang** [comment]
If you are feeling brave, you can also separate out genotyping as activity in itself that was done independently and before the animal is used for physiology.

**Comment by yarikoptic** [comment]
I would assume that this was addressed in the context of the dandi-schema work.
