### ISSUE TITLE
tools/migrate-dandisets.py: error out if no credentials available

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#532]
script got too much life/use, and I stepped into this at least two times already -- if no credentials, it seems to exit with 0 so I get
```
*$> { for d in 0000*; do python /home/yoh/proj/dandi/dandi-cli/tools/migrate-dandisets.py https://api.dandiarchive.org/api  $DANDI_API_TOKEN $d && echo "$d ok" || echo "$d failed"; done; } | tee /tmp/migrate-dandisets-3.log
000003 ok
000004 ok
```
only then recalling that I have not seen message "Creating ..." which is what should be there if all good

Since I see it used at least a few more times, might be nice to have it fixed up

**Comment by jwodder** [comment]
@yarikoptic When this happens, is `$DANDI_API_TOKEN` unset?  That results in the script just being run as `migrate-dandisets.py https://api.dandiarchive.org/api $d`, i.e., with an empty list of Dandisets, so it does nothing.  I suggest enclosing `$DANDI_API_TOKEN` in double-quotes so that, when it's unset, an empty string will be passed in its place.

**Comment by yarikoptic** [comment]
Yeah, should just do that, thanks!
