### ISSUE TITLE
Session has disappeared from filename construction

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#614]
The file in dandiset 69 is a file from another dandiset. When you see the metadata, session is there. But it is not in the name. https://api.dandiarchive.org/api/dandisets/000069/versions/draft/assets/93b8e5ef-69fd-4ac1-863f-5ff1f9210554/

This was also reported by cody when fixing one of the dandisets.

If this is intentional, it should be made clear. I have no problems with filenames being as short as possible with changes made only when disambiguating. However I don't think the cli is ready for that yet. For example, adding a new file that runs into a clash. It may also be disruptive in the short run in terms of human expectations.

**Comment by yarikoptic** [comment]
uff... first I thought that it was just a single asset among many and it didn't have session while others had: which could have happened is that it was an incremental `organize` of more files (from the same session) into an existing dandiset. Since session is optional (relates to prior discussion in #69) and was the same among multiple files, it was not added.

But apparently it is just a single asset in that dandiset: https://gui.dandiarchive.org/#/dandiset/000069/draft/files?location=sub-anm106211%2F  and it is exactly the discussion we had in #69 and "optional" nature of the session field -- we do not populate it unless it would help to resolve conflicts.  So it did not "disappear", it was never in the filename to  begin with.

**Comment by satra** [comment]
ok if it is optional, then indeed we should consider what partial updates means (like cody ran into): https://github.com/dandisets/000053/issues/1 

this seems to imply some logic needed beyond just naming locally.

**Comment by yarikoptic** [comment]
for partial updates (also attn @CodyCBakerPhD), I think we should just instruct people ATM to follow up with a subsequent run of `dandi organize -f move` in that dandiset **after** "they are done" with all desired incremental additions.  The reason is that loading metadata does take time (although we cache it) so on a large dandiset it could take awhile, and thus loading metadata from all the files in dandiset should not be done "all the time" for incremental updates.

I have now tried on the 000053, where I first renamed two files into "without session":

```
drogon:/mnt/backup/dandi/trash/000053
*$> git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    sub-npI1/sub-npI1_ses-20190415_behavior+ecephys.nwb
        deleted:    sub-npI1/sub-npI1_ses-20190415_behavior.nwb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        sub-npI1/sub-npI1_behavior+ecephys.nwb
        sub-npI1/sub-npI1_behavior.nwb
```

and then did 

```
drogon:/mnt/backup/dandi/trash/000053
$> dandi organize -f move
2021-05-05 14:33:39,855 [    INFO] We will organize . in-place
2021-05-05 14:33:39,861 [    INFO] Loading metadata from 359 files
...
2021-05-05 14:34:09,672 [    INFO] 16 out of 359 paths are not unique. We will try adding _obj- based on crc32 of object_id
2021-05-05 14:34:09,915 [    INFO] Organized 2 out of 359 paths (357 same existing skipped). Visit ./
2021-05-05 14:34:09,916 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210505183338Z-5780.log
```
and ended up with
```
$> git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   dandiset.yaml

no changes added to commit (use "git add" and/or "git commit -a")
```
due to 
```
$> git diff
diff --git a/dandiset.yaml b/dandiset.yaml
index 7fd865d..0e1d9f8 100644
--- a/dandiset.yaml
+++ b/dandiset.yaml
@@ -100,3 +100,4 @@ repository: https://dandiarchive.org/
 schemaVersion: 0.3.0
 studyTarget: []
 wasGeneratedBy: []
+number_of_subjects: 34
```
which I think we should get rid off, right @satra?

**Comment by satra** [comment]
@yarikoptic - doesn't this assume you have all the files locally in place? what if you just converted one recording as cody did in his case?

**Comment by satra** [comment]
> which I think we should get rid off, right @satra?

yes, we should get rid of changes to dandiset.yaml from the CLI side.

**Comment by yarikoptic** [comment]
> @yarikoptic - doesn't this assume you have all the files locally in place? 

yes it does. 

> what if you just converted one recording as cody did in his case?

Further thoughts are in https://github.com/dandi/dandi-cli/issues/69#issuecomment-832932858 . Let's continue discussion there.  As I have mentioned, nothing really "disappeared" so I would just close this issue in favor of #69 .

for dandiset.yaml changes -- submitted #615 PR.
