### ISSUE TITLE
upload using `.` to indicate present directory did not work

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#641]
in dandiset 105 to move the data, the following command was used for trying upload

`DANDI_DEVEL=1 dandi upload --allow-any-path --validation skip .`

the above did not send any files but the following command did do the appropriate thing.

`DANDI_DEVEL=1 dandi upload --allow-any-path --validation skip sub-mgh191021520`

**Comment by yarikoptic** [comment]
@jwodder please double confirm that 
- `upload .` works 
- I think the actual reason is that `sub-mgh191021520` was not uploaded since it was a symlink to some directory outside

Please issue a warning if our traversal of a directory encounters a directory symlink which we do not "follow": state that symlinked directories are not supported (should be done after all exclusions already applied so we do not warn needlessly)

**Comment by jwodder** [comment]
@yarikoptic 

> please double confirm that `upload .` works

Confirmed.

> Please issue a warning if our traversal of a directory encounters a directory symlink which we do not "follow"

Are you sure it wouldn't be preferrable to support directory symlinks?  That should just require passing `followlinks=True` to `os.walk()` in `find_files()`.

**Comment by yarikoptic** [comment]
> > Please issue a warning if our traversal of a directory encounters a directory symlink which we do not "follow"
> 
> Are you sure it wouldn't be preferrable to support directory symlinks? That should just require passing `followlinks=True` to `os.walk()` in `find_files()`.

we could but that would open a pandora box of circular links we would need to guard for... given that typically people should `dandi organize` into the dandiset, I feel that staying simpler/safer would be better at least for now.
