### ISSUE TITLE
asset updates: where things should go in metadata

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#642]
"subject_id" -> in current wasAttributedTo
"session_id"  -> in current wasGeneratedBy
"tissue_sample_id"  -> in current wasDerivedFrom
"slice_id"  -> in current wasDerivedFrom
"cell_id" -> in current wasDerivedFrom
"probe_ids" -> ???
"obj_id" -> add to "wasDerivedFrom" (this could be derived from an NWB file with identifier obj id?)
"modalities" -> see below
"extension" -  in current contentType

NB edited by @yarikoptic for uniformity and to reflect discussion below

we do need to fill both approach and measurementTechnique.  @bendichter started this: https://docs.google.com/spreadsheets/d/1x6aI5e7uWwyUJf_S1RyYkmOW-OzodLcRserZVq4DL2A/edit#gid=0

we will need to curate a list of named approaches and techniques from tom's list (i would use dandi readable prefixes that map via sameas to tom's list, unless tom's already has readable prefixes.

anything missing?

cc: @yarikoptic @bendichter @tgbugs

we need to finalize this and rerun modification of asset metadata before we can generate assetsSummary. so this is a bit urgent to get going.

**Comment by yarikoptic** [comment]
re modalities: we were (ab)using "module" and as such discriminated between "ecephys" and "icephys". Table has "modality term" which unifies them both into "electrophysiology".
To comprise all metadata needed for file naming (#618) we would need to either 
- `1.` keep the difference (introduce "submodality term"?) or
- `2.` abandon discrimination and have only `electrophysiology` and come up with a new suffix for filenames (`_ephys`?)

I feel that `1.` is pragmatically useful, e.g. someone interested to test a new spike sorting  algorithm would look for extracellular recordings, or even a pair of ecephys + icephys.

@satra by `-> in current derivation` you meant `-> in current wasDerivedFrom` right? (just making sure I don't miss anything)

>"probe_ids" -> ???

shouldn't it 

- become part of `wasGeneratedBy`?
- be a list of `Probe(Hardware)` where `Hardware` would also be added to parallel `Software` we have?

or may be there is already some standardized representation?  

edit: [old exchange from 2012](https://lists.w3.org/Archives/Public/public-prov-wg/2012Feb/0159.html) suggests that Software and Hardware should be agents.  In our model `Software` is not subclass of `Agent` and `Agent` has `schemaKey: Literal["Software"] = Field("Agent", readOnly=True)` so I am a bit confused on the mapping of agents and non-agents here ;)

**Comment by yarikoptic** [comment]
> "obj_id" -> "wasDerivedFrom" (this could be derived from an NWB file with identifier obj id?)

yeah, sounds right semantically to my LD-ignorant ear ;)

We had been fusing a notion and properties of a `File` into `BareAssetMeta`. May be we are finally doomed to introduce `File` and then subclasses such as `NWBFile(HDF5File)` which then would have that `object_id` and could be explicitly included into `wasDerivedFrom` for the `BareAssetMeta`?

That would kinda make it nice and "dandi" semantically since 

- Asset is our construct which is indeed derived from some file (ATM) and in the future possibly from collections of those (e.g. a Zarr directory -- https://github.com/dandi/dandi-api/pull/295; note that technically directory is a file kinda ;))
- all currently 1-to-1 mapped attributes (size, encodingFormat, dateModified, etc) would then gain a new meaning as an aggregate (in size, dates etc)

**Comment by satra** [comment]
1 vs 2: in the metadata you will have access to approach and technique, and you could still map that to modality for filename construction. i.e. in my mind the main thing is put the details in metadata and then construct the filename from the metadata.

re: derivation: yes, in current wasDerivedFrom

re: probe: i still don't understand a probe id. @bendichter - what is a probe? 

re: asset meta: i would like to stay away from the notion of an asset becoming a collection. but subclassing for specific additional properties is ok with me. in bids datasets we will have files which are participant agnostic, so `wasAttributedTo` should become optional for those files. so `BareAssetMeta` becomes generic to any `File`, and then properties become restricted/added/enhanced for specific types of assets. this may also simplify metadata extraction/validation  by tying to asset classes.

**Comment by yarikoptic** [comment]
> i.e. in my mind the main thing is put the details in metadata and then construct the filename from the metadata.

agree on that.  But I do not see `approach` in the @bendichter 's table so not sure how well that one "quantize", and `technique` I guess could be the one in "method term" column but that one is too verbose to be easily usable for filename construction.

> but subclassing for specific additional properties is ok with me.

subclassing what?  we can't/mustn't subclass `*AssetMeta` since we already have `BareAssetMeta -> AssetMeta -> PublishedAssetMeta` so we took subclassing to reflect the dimension of "publication state".  We shouldn't start mixing that in with another dimension (such as "AssetType" of come kind). That is why we need to "delegate" one way or another.

**Comment by bendichter** [comment]
@satra a probe is a device you implant into the brain to record neural activity, esp. extracellular electrophysiology, e.g. the [Neuropixel Probe](https://www.neuropixels.org/probe).

I agree that separating icephys and ecephys is useful. I have found sometimes that they are combined together but they are really quite different techniques and are used differently.

I can add "approach" and "technique" to this table if that would be helpful.

**Comment by bendichter** [comment]
"approach" ended up being basically the same as modality

**Comment by satra** [comment]
thanks @bendichter - i don't think changing the column names are required, but you could. are the values in those columns from tom's labels?

**Comment by bendichter** [comment]
I just went through and made sure they matched up with the labels in the NIF-Ontology repo

**Comment by tgbugs** [comment]
I'm doing a similar run through the SPARC data model at the moment and I think everything here is in order.

Taking a subset of the approaches and mapping them to the common approaches is fine, they were originally derived from what BCDC, SPARC, and HBP were doing. If you encounter any new approaches that you need for your own uses drop an issue in the NIF-Ontology issue tracker so we can add them since eventually someone else will probably want/need them.

Relatedly, I'm looking for an abstraction of probe that covers things like nerve cuffs, but I think it winds up being `instrument` with the specific type determined by RRID. Unfortunately `instrument` doesn't indicate that there is a map from electrodes/contacts that have spatial location to channels that were recording data from that location, so I wind up needing types that are equivalent to `hasPart some (MeasurementDevice and hasLocation some SpatialLocation and hasIdentifierInData some number)`.

**Comment by satra** [comment]
@tgbugs - i don't have a good sense of where to put probe id. in the attached PR i put it in an assayType associated with tissuesample or the highest level sample, but i'm not sure that's the best place. any thoughts?

**Comment by tgbugs** [comment]
Short version. I think the only tractable place is to have it attached to a process/activity (generation of a single or multiple files, run, session, experiment, study, etc.). For activities you have to use your activity part extension because of things like chronic implants that might be used for the life of the subject. I don't see any general way to attach it to samples or subjects.

Long version.

I don't think sample works because probes can go directly into an awake behaving animal. They are more similar to instruments, though usually they aren't reused across subjects, sometimes they can be reused across trials e.g. in the case of single sharp extracellular electrodes, but then they are only reused when their electrical properties are within the right range (high impedance iirc).

The fully developed ontology/data model for this centers around the concept of a rig, basically an experimental measurement/probing device with lots of parts, some of which change with each trial/run, but at the end of the day all of which are the Argo, parts change, the rig stays the same. The problem for the data model is that sometimes that exact components matter, so we want to track them.

I'm going to assert that we do not want to do the full, track every single pipette, modelling of the rig. That said, for patch clamp when people record the resistance of the pipette they are actually doing that, so it might not be so insane to have a record for the exact pipette that gets switched out every cell, and the electrode that gets re-plated with silver every 100 cells (or something like that).

So what do we want to record? I think mostly what we want to record is the fact that there are multiple different probes that are distinct and that have different (or possibly similar) locations, and that map to different sets of channels. They may also have different types (e.g. in hippopotamus slices there is a curled stimulating electrode and a patch pipette). Location/site, type, identity, and mapping to channels via electrodes/contacts/pipette-tips/etc are all conflated in the concept of a probe and different rigs care about different things and make different measurements of the probes in question. In long, the diversity of use cases doesn't help us here, because different techniques care about different things, some can discard probe identity because it is a single chronic implant and all that matters is type and location, in other cases the resistance of every single pipette could be important.

**Comment by satra** [comment]
thanks for the detailed response. we will probably need a better way to associate an experimental rig. for the moment i moved it near a session.
