### ISSUE TITLE
adjust nwb metadata extraction only for nwb files

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#730]
using encodingFormat only do metadata extraction for nwb files. right now, for non-nwb datasets, the logs are filled with errors about unable to open nwb file. to the user that seems unnecessary.

**Comment by yarikoptic** [comment]
logs of what? calling what function?  
we do populate encodingFormat for non-nwb files as well since recently. get_asset_metadata (https://github.com/dandi/dandi-cli/blob/HEAD/dandi/metadata.py#L700), used e.g. by `upload` falls back to get_default_metadata which populates them.

Need more information to grasp what/where the problem is

**Comment by satra** [comment]
dandi-cli logs is full of.

> 2021-07-22T09:18:12-0400 [INFO    ] dandi 885255:140460640769792 Failed to extract NWB metadata from sub-MITU01/ses-20210709h05m43s00/microscopy/sub-MITU01_run-1_sample-154_stain-LEC_chunk-9_transforms.json: OSError: Unable to open file (file signature not found)
