### ISSUE TITLE
cli trying to upload blob that exists

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#736]
@jwodder - perhaps you could use the etag to see why cli would try to reupload

```
2021-07-23T09:28:08-0400 [INFO    ] dandi 1689420:140149865748288 os.getcwd() = /mnt/beegfs/satra/zarrhdf/dandi
2021-07-23T09:28:09-0400 [DEBUG   ] dandi 1689420:140149865748288 No newer (than 0.23.2) version of dandi/dandi-cli found available
2021-07-23T09:28:10-0400 [DEBUG   ] dandi 1689420:140149865748288 GET https://api.dandiarchive.org/api/auth/token
2021-07-23T09:28:10-0400 [DEBUG   ] dandi 1689420:140149865748288 Response: 200
2021-07-23T09:28:10-0400 [DEBUG   ] dandi 1689420:140149865748288 Found identifier DANDI:000108 in top level 'identifier'
2021-07-23T09:28:10-0400 [DEBUG   ] dandi 1689420:140149865748288 GET https://api.dandiarchive.org/api/dandisets/000108/
2021-07-23T09:28:10-0400 [DEBUG   ] dandi 1689420:140149865748288 Response: 200
2021-07-23T09:28:12-0400 [INFO    ] dandi 1689420:140149865748288 Found 1 files to consider
2021-07-23T09:28:12-0400 [DEBUG   ] dandi 1689420:140136165803776 GET https://api.dandiarchive.org/api/dandisets/000108/versions/draft/assets/
2021-07-23T09:28:12-0400 [DEBUG   ] dandi 1689420:140136165803776 Response: 200
2021-07-23T09:28:12-0400 [DEBUG   ] dandi 1689420:140136165803776 /mnt/beegfs/satra/zarrhdf/dandi/sub-MITU01/ses-20210614h15m30s08/microscopy/sub-MITU01_run-1_sample-169_stain-LEC_chunk-1_spim.h5 has no nwb_version
2021-07-23T09:28:12-0400 [INFO    ] dandi 1689420:140136165803776 Failed to extract NWB metadata from sub-MITU01/ses-20210614h15m30s08/microscopy/sub-MITU01_run-1_sample-169_stain-LEC_chunk-1_spim.h5: ValueError: No data_type found for builder root
2021-07-23T09:28:12-0400 [DEBUG   ] dandi 1689420:140136165803776 Calculated dandi-etag of fd0ac2f4aec518834dca9ff1a077ffce-722 for sub-MITU01/ses-20210614h15m30s08/microscopy/sub-MITU01_run-1_sample-169_stain-LEC_chunk-1_spim.h5
2021-07-23T09:28:12-0400 [DEBUG   ] dandi 1689420:140136165803776 sub-MITU01/ses-20210614h15m30s08/microscopy/sub-MITU01_run-1_sample-169_stain-LEC_chunk-1_spim.h5: Beginning upload
2021-07-23T09:28:12-0400 [DEBUG   ] dandi 1689420:140136165803776 POST https://api.dandiarchive.org/api/uploads/initialize/
2021-07-23T09:28:12-0400 [DEBUG   ] dandi 1689420:140136165803776 Response: 409
2021-07-23T09:28:12-0400 [DEBUG   ] dandi 1689420:140136165803776 Error 409 while sending POST request to https://api.dandiarchive.org/api/uploads/initialize/: "Blob already exists."
2021-07-23T09:28:12-0400 [DEBUG   ] dandi 1689420:140136165803776 sub-MITU01/ses-20210614h15m30s08/microscopy/sub-MITU01_run-1_sample-169_stain-LEC_chunk-1_spim.h5: Blob already exists on server
2021-07-23T09:28:12-0400 [DEBUG   ] dandi 1689420:140136165803776 sub-MITU01/ses-20210614h15m30s08/microscopy/sub-MITU01_run-1_sample-169_stain-LEC_chunk-1_spim.h5: Assigning asset blob to dandiset & version
2021-07-23T09:28:12-0400 [DEBUG   ] dandi 1689420:140136165803776 GET https://api.dandiarchive.org/api/dandisets/000108/versions/draft/assets/
2021-07-23T09:28:12-0400 [DEBUG   ] dandi 1689420:140136165803776 Response: 200
2021-07-23T09:28:12-0400 [DEBUG   ] dandi 1689420:140136165803776 POST https://api.dandiarchive.org/api/dandisets/000108/versions/draft/assets/
2021-07-23T09:28:12-0400 [DEBUG   ] dandi 1689420:140136165803776 Response: 409
2021-07-23T09:28:12-0400 [DEBUG   ] dandi 1689420:140136165803776 Error 409 while sending POST request to https://api.dandiarchive.org/api/dandisets/000108/versions/draft/assets/: "An asset with that path already exists"
2021-07-23T09:28:12-0400 [DEBUG   ] dandi 1689420:140149865748288 GET https://api.dandiarchive.org/api/dandisets/000108/versions/draft/assets/
2021-07-23T09:28:12-0400 [DEBUG   ] dandi 1689420:140149865748288 Response: 200
2021-07-23T09:28:12-0400 [INFO    ] dandi 1689420:140149865748288 Logs saved in /home/satra/.cache/dandi-cli/log/20210723132808Z-1689420.log
```

**Comment by jwodder** [comment]
@satra Exactly what behavior here do you have a problem with?

**Comment by satra** [comment]
that the CLI is trying to re-upload a blob that exists according to the server, which returns a 409. CLI should not be trying to re-upload a blob that exists.

**Comment by satra** [comment]
also bringing @dchiquito into this thread. there are two 409s in the above log:

1. for blob exists
2. for path exists

for the mortal user we need to know what to do when these errors happen.

**Comment by jwodder** [comment]
@satra Be more precise.  What is the earliest point in the logs that you think the client should do something different?

**Comment by satra** [comment]
those 409s should not happen ever (i think). those errors indicate something is problematic in the interaction between the CLI and the API. i think CLI logic should be able to address this properly.

the first 409, CLI should not try to initialize an upload
the second 409, the CLI should use PUT not POST

**Comment by jwodder** [comment]
@satra The first 409 is 100% intentional and will not change.  The 409 response to the request to start an upload is how the client knows that the blob already exists on the server.

**Comment by yarikoptic** [comment]
I think it is due to https://github.com/dandi/dandi-api/issues/441 isn't it?

**Comment by satra** [comment]
@jwodder - i thought the check whether a blob exists or not happens with this api route (`/blobs/digest/`)

**Comment by yarikoptic** [comment]
> @jwodder - i thought the check whether a blob exists or not happens with this api route (`/blobs/digest/`)

if it is caused by https://github.com/dandi/dandi-api/issues/441 (do you have identical files you are uploading?) -- then it is "too late" -- files were not there before uploading multiple instances of them with the same digest

**Comment by satra** [comment]
@yarikoptic - that should not be the issue here i think. the blob is already there and i'm not doing simultaneous uploads of the same blob.

**Comment by yarikoptic** [comment]
> @yarikoptic - that should not be the issue here i think. the blob is already there and i'm not doing simultaneous uploads of the same blob.

ah, right... so it all boils down to initial 409 is Ok, we react to it properly but then
```
2021-07-23T09:28:12-0400 [DEBUG   ] dandi 1689420:140136165803776 POST https://api.dandiarchive.org/api/dandisets/000108/versions/draft/assets/
2021-07-23T09:28:12-0400 [DEBUG   ] dandi 1689420:140136165803776 Response: 409
2021-07-23T09:28:12-0400 [DEBUG   ] dandi 1689420:140136165803776 Error 409 while sending POST request to https://api.dandiarchive.org/api/dandisets/000108/versions/draft/assets/: "An asset with that path already exists"
```
I think is possibly some new or not yet tested (?) behavior of "reupload a previously uploaded file under a new filename, which also already known to the dataset version".  IIRC we did not decide to introduce any guards on dandi-api side for overrides, so in principle it should dandi-api which should handle it instead of returning 409 ?  Or do we want to provide guards for overwrites at dandi-api side, causing it always to 409 when overwriting and leaving it to client to first delete that asset? (wasn't like that I believe in our original thinking)

**Comment by satra** [comment]
IMO:

1. CLI should check if blob is there. if not upload (seems like this is in place, but should just use a different endpoint instead of trying to initialize an upload and thereby checking)
2. CLI should check if asset path is there and then use PUT instead of POST. the API just introduced the 409 on trying to POST an asset to a path that exists. (this was the duplication issue we saw with the same dataset earlier)

seems both are handleable at the CLI level.

**Comment by yarikoptic** [comment]
> 1. CLI should check if blob is there. if not upload (seems like this is in place, but should just use a different endpoint instead of trying to initialize an upload and thereby checking)

nah... that would cause yet another race condition since operation of "check and then do or not" isn't atomic, so you would then even more likely end up in the same situation anyways whenever e.g. parallel uploads would upload the same sizeable blob. I believe it was conscious a decision to avoid that at least for this part and just initiate the upload and react on return value, which is what we do now. I think it is ok as is - that 409 you see is at DEBUG log level, and is ok at that.

> 2\. CLI should check if asset path is there and then use PUT instead of POST. the API just introduced the 409 on trying to POST an asset to a path that exists. (this was the duplication issue we saw with the same dataset earlier)

in a short term -- "may be", since it again opens the door wider for race conditions and thus flaky operation. Reacting to 409 upon POST and switching to PUT for a specific asset id (if only 409 response included it) would also be racy, so in the long term neither of those ways wouldn't be a "solid" mechanism. Also I am not yet sure what PUT would do if we are to provide metadata which overwrites asset at some other path -- would it work or 409? ;-)  Note: we already have a race condition anyways since we first check if there is an asset at the path, and handle according to `--overwrite` option.  That is why in a short term indeed we should probably just use PUT instead of POST if we know which asset we are to "replace".  @jwodder - please do that for now, with a nice test which would also test on a use case where it is already a known blob. But note I am not yet sure if `PUT` would not 409 and either it would replace an existing asset or breed one more.

I started to write up my thoughts in an issue against dandi-api since PUT semantic is not clear (and doc in swagger just says "Update the metadata of an asset." without hinting on replacement or what would happen in case of path in metadata change or absence), but I guess I will just wait for @jwodder to discover details of behavior.

**Comment by satra** [comment]
indeed we can potentially get into race conditions, but highly unlikely in the same dataset, even if used by multiple owners or the same owner across machines (consider parallel uploads in network bottlenecked machines). 

currently `PUT` or `POST` always breeds new asset. 

if we wanted `PUT` to not breed a new asset id, that's a discussion we need to have. there may be certain advantages and disadvantages to that, and it's going to be a semantic call. at present i prefer the current scenario of minting new asset id on PUT.

**Comment by jwodder** [comment]
@yarikoptic The upload code already uses PUT if uploading an asset to a path that already exists; [see here](https://github.com/dandi/dandi-cli/blob/457c1e519c3daa75f729f686e963e637e5a78e91/dandi/dandiapi.py#L696-L712).

@satra Exactly what was going on with the Dandiset you were uploading?  Had the exact same asset been uploaded to the same path before, or did something change in the local Dandiset between uploads?

**Comment by satra** [comment]
i think the version of the CLI changed, which would change the metadata. so between uploads the local metadata changed.

**Comment by yarikoptic** [comment]
> currently `PUT` or `POST` always breeds new asset.
> 
> if we wanted `PUT` to not breed a new asset id, that's a discussion we need to have. there may be certain advantages and disadvantages to that, and it's going to be a semantic call. at present i prefer the current scenario of minting new asset id on PUT.

I wasn't exhaustive/confusing in my description:  both PUT and POST should breed new assets and thus asset_ids.  My point was about what is happening to an already existing asset?  if `PUT` is to "update an asset", then it should "remove" the previous asset from the dandiset_version, and thus in effect "replace" it with a new one, which might or might not have a different path (depending on what metadata had, right), and that is where I was afraid (and @jwodder /code seems to confirm) that `PUT` is not doing that and issues 409 since both old and new assets exist and point to the same path.

**Comment by yarikoptic** [comment]
Let's bring @dchiquito into discussion since it seems to boil down to dandi-api:  does `PUT` on an asset in a dandiset removes (from dandiset_version not assets) previous asset first before creating/placing a new one "to replace the old one"? if it does not -- then we would be running into recently introduced protection to not breed duplicate assets.

**Comment by dchiquito** [comment]
PUT adds the new asset and removes the old asset in a transaction: https://github.com/dandi/dandi-api/blob/master/dandiapi/api/views/asset.py#L236-L248

I'm not sure why we're discussing `PUT` here. Satra's logs indicate that the 409 related to the duplicate path was returned from a `POST`. The [code John linked](https://github.com/dandi/dandi-cli/blob/457c1e519c3daa75f729f686e963e637e5a78e91/dandi/dandiapi.py#L696-L712) looks correct to me, so my suspicion is that there was a race condition where a different client registered an asset at that path between the GET and the POST.

**Comment by satra** [comment]
> my suspicion is that there was a race condition where a different client registered an asset at that path between the GET and the POST.

would be very unlikely. since i am the only one uploading this data. so remains a mystery how this knot was created.

**Comment by satra** [comment]
the discussion for PUT is that an asset check for existence of an asset at a given path should then result in a PUT and not a POST.

**Comment by yarikoptic** [comment]
indeed I have missed that it was a POST, whenever it should have been PUT.  Not sure yet what is going on either.  Would be nice if we could reproduce on a small example.   
@jwodder 's [code](https://github.com/dandi/dandi-cli/blob/457c1e519c3daa75f729f686e963e637e5a78e91/dandi/dandiapi.py#L516) working around the limitation of API (which can in fact contribute to the racing) to not be able to check for exact path (filed https://github.com/dandi/dandi-api/issues/444) seems right, it is a bit "python idiosyncratic" and thus I wouldn't be surprised that somehow it fell through some crack.

**Comment by yarikoptic** [comment]
In the `iter_upload_raw_asset` you @jwodder  [pointed to](https://github.com/dandi/dandi-cli/blob/457c1e519c3daa75f729f686e963e637e5a78e91/dandi/dandiapi.py#L696-L712) let's just 
- avoid `self.get_asset_by_path(asset_path)` - as I have mentioned in https://github.com/dandi/dandi-api/issues/444 could be inefficient in its current manifestation, and adds yet another race condition point
- just react on 509 and switch from POST to PUT if it happens -- we have done check for `existing` above and can't avoid race condition ATM altogether but at least could may be minimize it this way.  The only race at this point could be a removal of an asset to happen between POST and PUT -- less likely IMHO

**Comment by jwodder** [comment]
@yarikoptic `get_asset_by_path(asset_path)` is required in order to get the ID of the asset to update with PUT.  Would calling that method only in response to a 409 be safe?

**Comment by yarikoptic** [comment]
> @yarikoptic `get_asset_by_path(asset_path)` is required in order to get the ID of the asset to update with PUT.

d'oh, right... so it was not an actionable idea :-/  

looking at the code, https://github.com/dandi/dandi-cli/blob/457c1e519c3daa75f729f686e963e637e5a78e91/dandi/dandiapi.py#L510:9 provides no guards for path to be relative - I wonder if that is a culprit here somehow since then `self.path == path` comparison could fail for the same path if path is abs on one side.  @satra -- did you use absolute paths in your invocation, do you remember?

In `upload.py` we use `extant = remote_dandiset.get_asset_by_path(str(relpath))`  so we do use `relpath` whenever `iter_upload_raw_asset(` uses `asset_path` which is coming from `asset_path = asset_metadata["path"]` and I have vague memory we had some issue relating to abs paths sneaking in.  I think we might want to add some guards, even if just an `assert` here where we assume it is relative.

but then we still ideally should avoid double `get_asset_by_path` invocation.  I think one of the viable ways is to add `replace_asset: Optional[str] = None` argument to `iter_upload_raw_asset` so that `upload` code, in case of replacing an asset, could pass it through.  If provided (and not `None`) -- use `PUT` with that `replace_asset` id not `POST`.  This way

- change semantic of `iter_upload_raw_asset` that it wouldn't silently replace an asset
- we do amplify the possibility for a race condition (in case some other asset uploaded to that path meanwhile)

but I think it would be actually for a benefit -- at least will be making it a bit more "solid" that we wouldn't be overwriting some other asset which we haven't "analyzed" for above, and also a bit faster avoiding 2nd invocation of `get_asset_by_path`.

> Would calling that method only in response to a 409 be safe?

what do you mean ?

**Comment by jwodder** [comment]
@yarikoptic 

> what do you mean ?

I mean, would you consider calling `get_asset_by_path(asset_path)` if & only if a 409 occurs when POSTing to be a viable solution?

**Comment by yarikoptic** [comment]
ah... well, could have been, unless the original issue is in that code/invocation (e.g. relative paths hypothesis above).  But I think we would be better of making this one to not do magical "replace an asset" unless instructed to do so (per my description above) altogether. WDYT about that ?

**Comment by satra** [comment]
> did you use absolute paths in your invocation, do you remember?

no. it was a relative path within the dandiset directory. and i believe i tried with both `.` syntax and the individual file. both resulted in the 509 error.

**Comment by jwodder** [comment]
@yarikoptic If `replace_asset` is added to `iter_upload_raw_asset()`, should the checks that are already in the method for a pre-existing asset be kept, or should the code just error if a race condition occurs?

**Comment by yarikoptic** [comment]
> > did you use absolute paths in your invocation, do you remember?
> 
@satra 

> no. it was a relative path within the dandiset directory. and i believe i tried with both `.` syntax and the individual file. both resulted in the 509 error.

what was your `--existing` setting, may be somehow related... ?

@jwodder 

> @yarikoptic If `replace_asset` is added to `iter_upload_raw_asset()`, should the checks that are already in the method for a pre-existing asset be kept, or should the code just error if a race condition occurs?

if you mean that invocation of `get_asset_by_path` - I think there should be no checks in `iter_upload_raw_asset` since we have that logic in higher level `upload` ATM.  docstring should just state that if intention is to replace an existing asset, then `replace_asset` should be provided and point to an existing in that dandiset version asset.

**Comment by yarikoptic** [comment]
interesting ... default is
```
                                  'refresh' - upload only if local modification time is ahead of the remote.
                                  [default: refresh]
```
@jwodder could you please analyze the logs (we have them on drogon now, `/mnt/backup/dandi/papertrail-logs/dandi-api/2021/07/23` for that date), and/or try to replicate the fail uploading/touch/reupload or alike? ideally we should get to the bottom of this, or we would just keep running into it.

**Comment by jwodder** [comment]
@yarikoptic I could not find anything relevant in the logs, and I was unable to reproduce the error locally.

**Comment by yarikoptic** [comment]
So, @jwodder let's then proceed with adding `replace_asset` as I described [above](https://github.com/dandi/dandi-cli/issues/736#issuecomment-886748171), unless you have some concerns about such approach.

**Comment by yarikoptic** [comment]
@satra  - you no longer have that file/situation any longer to try to reproduce and see if #743 somehow magically addresses it, do you?

**Comment by satra** [comment]
that is correct. i manually fixed the issue.

**Comment by yarikoptic** [comment]
I guess we will need to wait for it to resurface one way or another to "resolve the mystery" since I am still not certain on what lead to it.
