### ISSUE TITLE
validate-bids should use lowest supported BIDS version for earlier ones

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#950]
per our face-to-face discussion, if BIDSVersion has no present schemadata -- use `1.7.0+012` we carry after issuing a warning about that. As for version comparison -- seems to NOT work with `semantic_version` we already use

```shell
(git)lena:~/proj/dandi/dandi-cli-master[master]git
$> python -c 'from semantic_version import Version; print(Version("1.7.0")<Version("1.7.0+012"))' 
False

$> python -c 'from semantic_version import Version; print(Version("1.7.0+011")<Version("1.7.0+012"))'
False

$> python -c 'from semantic_version import Version; print(Version("1.7.0+013")<Version("1.7.0+012"))'
False
```
so let's not sweat about that for now with all the `+`s we have ATM.

**Comment by TheChymera** [comment]
Solved in https://github.com/dandi/dandi-cli/pull/955/commits/5fc7b0652e8eb9a998e12e84f7273e12e062f21e other than not presenting a warning. Not sure what sort of warning would be appropriate...

As for version comparison Python referencing of the ASCII table has us covered:

```python
>>> "1.7.0"<"1.7.0+012"
True
>>> "1.7.0+011"<"1.7.0+012"
True
>>> "1.7.0+013"<"1.7.0+012"
False
```

AFAICT the only surprises that this could cause are due to the fact that ASCII lists uppercase before lowercase, so:

```python
>>> "1.7.0+012+DANDI002"<"1.7.0+012+dandi001"
True
```

**Comment by yarikoptic** [comment]
I would prefer to avoid relying on plain string comparison of semantic versions composed from numbers, could just bite somehow unexpectedly e.g
```
>>> "1.7.0+012"< "1.7.0+99"
True
```
it is just a matter of semver to have "Identifiers MUST NOT be empty. Build metadata MUST be ignored when determining version precedence. "

<details>
<summary>although difference between <= and == and < confuses me -- may be a bug in semver?</summary> 

```python
$> python3 -c 'from semantic_version import Version; print(Version("1.7.0")==Version("1.7.0+012"))'
False

$> python3 -c 'from semantic_version import Version; print(Version("1.7.0")<Version("1.7.0+012"))'
False

$> python3 -c 'from semantic_version import Version; print(Version("1.7.0")<=Version("1.7.0+012"))'
True

```
</details>

hence we should ignore it is as well.  I gave a sketch for possible tune up in https://github.com/dandi/dandi-cli/pull/955/files#r852231652

**Comment by TheChymera** [comment]
> `"1.7.0+012"< "1.7.0+99"`
I thought the 3-digit length is fixed... Ok then :( I really liked the idea of leveraging plain string comparison, though, since it's refreshingly simple :)

**Comment by TheChymera** [comment]
Revisiting this, since `semantic_version` doesn't like our DANDI nomenclature:

```python
>>> from semantic_version import Version
>>> Version("1.7.0+012")<=Version("1.7.0+012+dandi001")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/semantic_version/base.py", line 105, in __init__
    major, minor, patch, prerelease, build = self.parse(version_string, partial)
  File "/usr/lib/python3.9/site-packages/semantic_version/base.py", line 311, in parse
    raise ValueError('Invalid version string: %r' % version_string)
ValueError: Invalid version string: '1.7.0+012+dandi001'
```

Given that this is the dandi-cli bundled version of the validator and we haven't even started trying to push `*.ngff` and `*.h5` yet — we need to fall back on `1.7.0+012+dandi001` and not `1.7.0+012`. Additionally, for upstream code, `semantic_version` isn't a dep, and given the minimal aspiration I think it makes sense to try to add zero libs.

At this point I'd say it would be best in both cases to either (1) accept the risk of plain string comparison, or (2) write a small function to implement the comparison we need. I thing the former is cooler :)

Leaving this open for now, pending your feedback on the solution. Warning and working string comparison is in as of https://github.com/dandi/dandi-cli/pull/955/commits/1a6d835213e6f64168e7850b3110c7a3b006e236 and previous.

**Comment by yarikoptic** [comment]
ok, you convinced me -- just do string comparison for now.

**Comment by yarikoptic** [comment]
I believe https://github.com/dandi/dandi-cli/pull/955 addressed this, and should have closed it .
