### ISSUE TITLE
add glob/regex support in the dandi library

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#979]
now that the api has support for glob/regex options in the `GET` for dandiset specific assets (endpoint: `/dandisets/{versions__dandiset__pk}/versions/{versions__version}/assets/`), it would be nice to have this option at least in the python library and perhaps in the cli for `ls`

**Comment by jwodder** [comment]
@satra To be clear: The new `glob` and `regex` query parameters filter the returned assets by matching on their paths, correct?  Or is it based on something else?

**Comment by satra** [comment]
yes, these are matched against their paths.

**Comment by jwodder** [comment]
@satra Is the `regex`-matching anchored to the start of the string?  I'm not getting any matches in testing.

**Comment by satra** [comment]
@mvandenburgh - any thoughts on @jwodder question

**Comment by mvandenburgh** [comment]
https://github.com/dandi/dandi-archive/issues/1047 is fixed. We removed regex support from the API because it opened us up to [some security vulnerabilities](https://en.wikipedia.org/wiki/ReDoS) (also see- https://www.postgresql.org/message-id/8823.1551589517%40sss.pgh.pa.us, one of the postgres devs acknowledging that postgres could be susceptible to an "evil regex")
